Lecture12 Task 1 - TestNG
mexal17/Automation pull request #15
Opened 2018-12-02 14:24 UTC by mexal17

Используя **TestNG** организовать тесты к **калькулятору**, написанному в качестве входного задания (**Lecture2 Task 3**):

1) cover calculator functionality with unit tests
2) use dependsOnMethods
3) use dataProvider
4) use xml suite

2018-12-03 11:34 UTC, ivan-pronin requested changes

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Task3/task3/Application.java
> +        double result = 0;
inline

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Task3/task3/Application.java
>          }
default?

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +        Thread.sleep(1000);
What's the reason of such sleeps?

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Task3/task3/Application.java
> +    public static double getResult(String operand, double firstDigit, double secondDigit) {
operand -> to enum

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Task3/task3/Application.java
> +    public static double getResult(String operand, double firstDigit, double secondDigit) {
`firstDigit` -> `firstOperand` - since it may be not a digit, but number
`secondDigit` -> `secondOperand`

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +        double result = 6;
inline all local vars

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +        double result = 6;
`result ` -> `expectedResult`

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +        double result = 40;
inline all local vars

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +                {1, 2, 3},
What about tests for negative, double numbers? You only test for positive integer values

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +        Assert.assertEquals(getResult("+", firstDigit, secondDigit), result, "Addition method failed");
You should create an instance of calculator to test it. This instance is then used in each unit test
All tests should be independent from each other

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +public class ApplicationTest {
-> CalculatorTests

2018-12-03 11:34 UTC, ivan-pronin commented on Lecture-2/Tests/calculator/ApplicationTest.java
> +    @Test(dependsOnMethods = "multiplicationTest")
Why is `subtractionTest` depends on `multiplicationTest`?

2018-12-04 19:11 UTC, mexal17 commented on Lecture-2/Task3/task3/Application.java
> +        double result = 0;
done

2018-12-06 09:46 UTC, ivan-pronin approved these changes

2018-12-06 12:59 UTC, merged