Lecture 16
mexal17/Automation pull request #17
Opened 2018-12-26 20:14 UTC by mexal17

Используя java + testNg + Webdriver

1)	 Написать тест который логинится на onliner.by  или любой другой интернет магазин 
2)	Выбирает рандомный продукт 
3)	Кладет в корзину
4)	Заходит в корзину и проверяет наличие выбранного товара

Использовать все виды локаторов : id, name, class, xpath, css

2018-12-27 13:01 UTC, ivan-pronin requested changes

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/pom.xml
> +            <version>3.13.0</version>
1. Use one version across similar dependencies, e.g. for all `org.seleniumhq.selenium` deps use one version.
2. Use latest available library versions: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java, so `3.141.59` is ok

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +import org.openqa.selenium.By;
package?

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG4 = "//button[@type='submit' and @class='auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full']";
REG1 ... REG4 - not clear variable names

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG3 = "//input[@type='password' and @class='auth-input auth-input_primary auth-input_base auth-form__input auth-form__input_width_full']";
I think `//input[@type='password']` is enough

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG4 = "//button[@type='submit' and @class='auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full']";
I think `//button[@type='submit']` will be enough

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG1 = "//div[@class='auth-bar__item auth-bar__item--text']";
Bad locator - difficult to understand, a lot of classes which may be changed

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG2 = "//input[@type='text' and @class='auth-input auth-input_primary auth-input_base auth-form__input auth-form__input_width_full']";
Bad locator - difficult to understand, a lot of classes which may be changed

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PUT_INTO_BASKET_CSS_SELECTOR = ".button.button_orange.button_middle.offers-list__button.offers-list__button_basket";
Bad locator - difficult to understand, a lot of classes which may be changed

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String OPEN_BASKET_XPATH = ".button.button_orange.button_middle.offers-list__button.offers-list__button_basket.offers-list__button_checked";
Bad locator - difficult to understand, a lot of classes which may be changed

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PROPERTY_KEY = "webdriver.chrome.driver";
Not clear var name - what property?

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PROPERTY_VALUE = "./src/test/resources/chromedriver.exe";
Not clear var name - what value?

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        wait.until(webDriver -> driver.findElement(By.xpath(REG4))).click();
Add assertion for successful registration / login

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        Assert.assertNotEquals(0, products.size());
Useless assertion - if products were empty you got exception at line `products.get(0).click()`

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        List<WebElement> items = wait.until(webDriver -> driver.findElements(By.className(ITEMS_CLASS_NAME)));
`ITEMS_CLASS_NAME` - not clear var name

2018-12-27 13:01 UTC, ivan-pronin commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        Assert.assertNotEquals(0, items.size());
Use `Assert.assertTrue(!items.isEmpty())` - it's easier to understand or
`Assert.assertFalse(items.isEmpty())`

2018-12-27 18:27 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG4 = "//button[@type='submit' and @class='auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full']";
done

2018-12-27 18:28 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG3 = "//input[@type='password' and @class='auth-input auth-input_primary auth-input_base auth-form__input auth-form__input_width_full']";
done

2018-12-27 18:28 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG4 = "//button[@type='submit' and @class='auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full']";
done

2018-12-27 18:28 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG1 = "//div[@class='auth-bar__item auth-bar__item--text']";
done

2018-12-27 18:29 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String REG2 = "//input[@type='text' and @class='auth-input auth-input_primary auth-input_base auth-form__input auth-form__input_width_full']";
done

2018-12-28 17:34 UTC, mexal17 commented on Lecture-16/pom.xml
> +            <version>3.13.0</version>
done

2018-12-28 17:35 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PUT_INTO_BASKET_CSS_SELECTOR = ".button.button_orange.button_middle.offers-list__button.offers-list__button_basket";
done

2018-12-28 17:35 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String OPEN_BASKET_XPATH = ".button.button_orange.button_middle.offers-list__button.offers-list__button_basket.offers-list__button_checked";
done

2018-12-28 17:38 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PROPERTY_KEY = "webdriver.chrome.driver";
done

2018-12-28 17:38 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +    private static final String PROPERTY_VALUE = "./src/test/resources/chromedriver.exe";
done

2018-12-28 17:39 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        wait.until(webDriver -> driver.findElement(By.xpath(REG4))).click();
done

2018-12-28 18:05 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        Assert.assertNotEquals(0, products.size());
done

2018-12-28 18:09 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        List<WebElement> items = wait.until(webDriver -> driver.findElements(By.className(ITEMS_CLASS_NAME)));
done

2018-12-28 18:10 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +        Assert.assertNotEquals(0, items.size());
done

2018-12-28 18:13 UTC, mexal17 commented on Lecture-16/src/test/java/OnlinerSiteTest.java
> +import org.openqa.selenium.By;
done

2019-01-24 07:48 UTC, ivan-pronin requested changes

2019-01-24 07:48 UTC, ivan-pronin commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +        elements.get(0).click();
`IndexOutOfBoundsException` if `elements.isEmpty()`

2019-01-24 07:48 UTC, ivan-pronin commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +    private void clickOnRandomElement(List<WebElement> elements){
This method should be moved to a separate class

2019-01-24 07:48 UTC, ivan-pronin commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +        System.setProperty(DRIVER_TYPE, DRIVER_PATH);
Move all driver related code to `WebDriverManager` class

2019-01-24 07:48 UTC, ivan-pronin commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +        driver.findElement(By.xpath(AUTH_BUTTON)).click();
`NoSuchElementException` if no element is found. Tests should handle such cases proactively

2019-01-24 07:48 UTC, ivan-pronin commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +        driver.findElement(By.xpath(AUTH_BUTTON)).click();
Extract appropriate method to separate classes - `SearchActions`, `ClickActions`, `SendKeysActions`, `WaitActions` and reuse in all test methods

2019-02-02 14:52 UTC, mexal17 commented on Lecture-16/src/test/java/website/OnlinerSiteTest.java
> +        elements.get(0).click();
done

2019-02-24 07:45 UTC, merged